"""empty message

Revision ID: 01cc7c443cb1
Revises: 
Create Date: 2021-02-20 19:15:28.807446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01cc7c443cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('previous_close', sa.REAL(), nullable=True),
    sa.Column('close', sa.REAL(), nullable=True),
    sa.Column('dollar_change', sa.REAL(), nullable=True),
    sa.Column('decimal_change', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('collection', sa.String(), nullable=True),
    sa.Column('info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    op.drop_table('indices')
    op.drop_table('index_tickers')
    # ### end Alembic commands ###
