"""empty message

Revision ID: 1acbe2a36aca
Revises: ceabac65ad8d
Create Date: 2021-02-19 17:24:58.138820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acbe2a36aca'
down_revision = 'ceabac65ad8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indices', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indices', 'name')
    # ### end Alembic commands ###
