"""empty message

Revision ID: 2a9fefbb0b55
Revises: d0d92c4cbdf8
Create Date: 2021-03-03 22:47:11.223862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9fefbb0b55'
down_revision = 'd0d92c4cbdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_info', sa.Column('last_updated', sa.DATE(), nullable=True))
    op.add_column('stock_info', sa.Column('twoHundredDayAverage', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_info', 'twoHundredDayAverage')
    op.drop_column('stock_info', 'last_updated')
    # ### end Alembic commands ###
