"""empty message

Revision ID: 7197e204a026
Revises: 56288389ad7d
Create Date: 2021-03-08 22:18:13.914370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7197e204a026'
down_revision = '56288389ad7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_info', sa.Column('exDividendDate', sa.DATE(), nullable=True))
    op.add_column('stock_info', sa.Column('trailingAnnualDividendRate', sa.REAL(), nullable=True))
    op.add_column('stock_info', sa.Column('trailingAnnualDividendYield', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_info', 'trailingAnnualDividendYield')
    op.drop_column('stock_info', 'trailingAnnualDividendRate')
    op.drop_column('stock_info', 'exDividendDate')
    # ### end Alembic commands ###
