"""empty message

Revision ID: 968136f2ac80
Revises: bc65e5c02ee0
Create Date: 2021-03-03 23:29:42.577260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968136f2ac80'
down_revision = 'bc65e5c02ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_log',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('table', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('exception', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure_log')
    # ### end Alembic commands ###
