"""empty message

Revision ID: 9f40c535534a
Revises: df88842d9059
Create Date: 2021-02-17 20:59:57.729647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f40c535534a'
down_revision = 'df88842d9059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('previous_close', sa.REAL(), nullable=True),
    sa.Column('close', sa.REAL(), nullable=True),
    sa.Column('real_change', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indices')
    op.drop_table('index_tickers')
    # ### end Alembic commands ###
