"""empty message

Revision ID: ceabac65ad8d
Revises: 9f40c535534a
Create Date: 2021-02-18 23:51:12.622346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceabac65ad8d'
down_revision = '9f40c535534a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indices', sa.Column('decimal_change', sa.REAL(), nullable=True))
    op.add_column('indices', sa.Column('dollar_change', sa.REAL(), nullable=True))
    op.drop_column('indices', 'real_change')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indices', sa.Column('real_change', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_column('indices', 'dollar_change')
    op.drop_column('indices', 'decimal_change')
    # ### end Alembic commands ###
