"""empty message

Revision ID: d0d92c4cbdf8
Revises: 94f92e43632b
Create Date: 2021-03-01 21:03:03.744627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d92c4cbdf8'
down_revision = '94f92e43632b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_changes', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('collection_changes', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_changes', sa.Column('data', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('collection_changes', 'date')
    # ### end Alembic commands ###
