- name: runners
  limit: 100
- name: dippers
  limit: 100
- name: price_range_high
  limit: 50
- name: price_range_low
  limit: 50
- name: high_short
  limit: 200
- name: high_dividend
  limit: 25
- name: high_dividend_sans_reit
  limit: 25
- name: dogs_of_the_dow
  limit: 10
